In [16]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd()

arquivo = BASE_DIR / "data" / "raw" / "consulta_cand_2026_BRASIL.csv"

df = pd.read_csv(
    arquivo,
    sep=";",
    encoding="latin1"
)

df.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO
0,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,3,CASADO(A),3,PARDA,999,OUTROS,-1,#NULO
1,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,602,PECUARISTA,-1,#NULO
2,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,1,SOLTEIRO(A),1,BRANCA,142,PROFESSOR DE ENSINO SUPERIOR,-1,#NULO
3,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,1,SOLTEIRO(A),3,PARDA,931,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",-1,#NULO
4,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),5,INDÍGENA,999,OUTROS,-1,#NULO

In [17]:
df.shape

(20721, 50)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20721 entries, 0 to 20720
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   DT_GERACAO                     20721 non-null  str
 1   HH_GERACAO                     20721 non-null  str
 2   ANO_ELEICAO                    20721 non-null  int64
 3   CD_TIPO_ELEICAO                20721 non-null  int64
 4   NM_TIPO_ELEICAO                20721 non-null  str
 5   NR_TURNO                       20721 non-null  int64
 6   CD_ELEICAO                     20721 non-null  int64
 7   DS_ELEICAO                     20721 non-null  str
 8   DT_ELEICAO                     20721 non-null  str
 9   TP_ABRANGENCIA                 20721 non-null  str
 10  SG_UF                          20721 non-null  str
 11  SG_UE                          20721 non-null  str
 12  NM_UE                          20721 non-null  str
 13  CD_CARGO                       20721 non-null  int64
 14  DS_CARGO                       20721 non-null  str
 15  SQ_CANDIDATO                   20721 non-null  int64
 16  NR_CANDIDATO                   20721 non-null  int64
 17  NM_CANDIDATO                   20721 non-null  str
 18  NM_URNA_CANDIDATO              20721 non-null  str
 19  NM_SOCIAL_CANDIDATO            20721 non-null  str
 20  NR_CPF_CANDIDATO               20721 non-null  int64
 21  DS_EMAIL                       20721 non-null  str
 22  CD_SITUACAO_CANDIDATURA        20721 non-null  int64
 23  DS_SITUACAO_CANDIDATURA        20721 non-null  str
 24  TP_AGREMIACAO                  20721 non-null  str
 25  NR_PARTIDO                     20721 non-null  int64
 26  SG_PARTIDO                     20721 non-null  str
 27  NM_PARTIDO                     20721 non-null  str
 28  NR_FEDERACAO                   20721 non-null  int64
 29  NM_FEDERACAO                   20721 non-null  str
 30  SG_FEDERACAO                   20721 non-null  str
 31  DS_COMPOSICAO_FEDERACAO        20721 non-null  str
 32  SQ_COLIGACAO                   20721 non-null  int64
 33  NM_COLIGACAO                   20721 non-null  str
 34  DS_COMPOSICAO_COLIGACAO        20721 non-null  str
 35  SG_UF_NASCIMENTO               20721 non-null  str
 36  DT_NASCIMENTO                  20721 non-null  str
 37  NR_TITULO_ELEITORAL_CANDIDATO  20721 non-null  int64
 38  CD_GENERO                      20721 non-null  int64
 39  DS_GENERO                      20721 non-null  str
 40  CD_GRAU_INSTRUCAO              20721 non-null  int64
 41  DS_GRAU_INSTRUCAO              20721 non-null  str
 42  CD_ESTADO_CIVIL                20721 non-null  int64
 43  DS_ESTADO_CIVIL                20721 non-null  str
 44  CD_COR_RACA                    20721 non-null  int64
 45  DS_COR_RACA                    20721 non-null  str
 46  CD_OCUPACAO                    20721 non-null  int64
 47  DS_OCUPACAO                    20721 non-null  str
 48  CD_SIT_TOT_TURNO               20721 non-null  int64
 49  DS_SIT_TOT_TURNO               20721 non-null  str
dtypes: int64(19), str(31)
memory usage: 7.9 MB

In [19]:
df.columns.tolist()

['DT_GERACAO',
 'HH_GERACAO',
 'ANO_ELEICAO',
 'CD_TIPO_ELEICAO',
 'NM_TIPO_ELEICAO',
 'NR_TURNO',
 'CD_ELEICAO',
 'DS_ELEICAO',
 'DT_ELEICAO',
 'TP_ABRANGENCIA',
 'SG_UF',
 'SG_UE',
 'NM_UE',
 'CD_CARGO',
 'DS_CARGO',
 'SQ_CANDIDATO',
 'NR_CANDIDATO',
 'NM_CANDIDATO',
 'NM_URNA_CANDIDATO',
 'NM_SOCIAL_CANDIDATO',
 'NR_CPF_CANDIDATO',
 'DS_EMAIL',
 'CD_SITUACAO_CANDIDATURA',
 'DS_SITUACAO_CANDIDATURA',
 'TP_AGREMIACAO',
 'NR_PARTIDO',
 'SG_PARTIDO',
 'NM_PARTIDO',
 'NR_FEDERACAO',
 'NM_FEDERACAO',
 'SG_FEDERACAO',
 'DS_COMPOSICAO_FEDERACAO',
 'SQ_COLIGACAO',
 'NM_COLIGACAO',
 'DS_COMPOSICAO_COLIGACAO',
 'SG_UF_NASCIMENTO',
 'DT_NASCIMENTO',
 'NR_TITULO_ELEITORAL_CANDIDATO',
 'CD_GENERO',
 'DS_GENERO',
 'CD_GRAU_INSTRUCAO',
 'DS_GRAU_INSTRUCAO',
 'CD_ESTADO_CIVIL',
 'DS_ESTADO_CIVIL',
 'CD_COR_RACA',
 'DS_COR_RACA',
 'CD_OCUPACAO',
 'DS_OCUPACAO',
 'CD_SIT_TOT_TURNO',
 'DS_SIT_TOT_TURNO']

In [20]:
df.isnull().sum()

DT_GERACAO                       0
HH_GERACAO                       0
ANO_ELEICAO                      0
CD_TIPO_ELEICAO                  0
NM_TIPO_ELEICAO                  0
NR_TURNO                         0
CD_ELEICAO                       0
DS_ELEICAO                       0
DT_ELEICAO                       0
TP_ABRANGENCIA                   0
SG_UF                            0
SG_UE                            0
NM_UE                            0
CD_CARGO                         0
DS_CARGO                         0
SQ_CANDIDATO                     0
NR_CANDIDATO                     0
NM_CANDIDATO                     0
NM_URNA_CANDIDATO                0
NM_SOCIAL_CANDIDATO              0
NR_CPF_CANDIDATO                 0
DS_EMAIL                         0
CD_SITUACAO_CANDIDATURA          0
DS_SITUACAO_CANDIDATURA          0
TP_AGREMIACAO                    0
NR_PARTIDO                       0
SG_PARTIDO                       0
NM_PARTIDO                       0
NR_FEDERACAO                     0
NM_FEDERACAO                     0
SG_FEDERACAO                     0
DS_COMPOSICAO_FEDERACAO          0
SQ_COLIGACAO                     0
NM_COLIGACAO                     0
DS_COMPOSICAO_COLIGACAO          0
SG_UF_NASCIMENTO                 0
DT_NASCIMENTO                    0
NR_TITULO_ELEITORAL_CANDIDATO    0
CD_GENERO                        0
DS_GENERO                        0
CD_GRAU_INSTRUCAO                0
DS_GRAU_INSTRUCAO                0
CD_ESTADO_CIVIL                  0
DS_ESTADO_CIVIL                  0
CD_COR_RACA                      0
DS_COR_RACA                      0
CD_OCUPACAO                      0
DS_OCUPACAO                      0
CD_SIT_TOT_TURNO                 0
DS_SIT_TOT_TURNO                 0
dtype: int64

In [21]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
DT_GERACAO,20721,1,24/08/2026,20721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HH_GERACAO,20721,1,16:31:10,20721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANO_ELEICAO,20721.0,NaN,NaN,NaN,2026.0,0.0,2026.0,2026.0,2026.0,2026.0,2026.0
CD_TIPO_ELEICAO,20721.0,NaN,NaN,NaN,2.0,0.0,2.0,2.0,2.0,2.0,2.0
NM_TIPO_ELEICAO,20721,1,ELEIÇÃO ORDINÁRIA,20721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NR_TURNO,20721.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
CD_ELEICAO,20721.0,NaN,NaN,NaN,6258.99749,0.070803,6257.0,6259.0,6259.0,6259.0,6259.0
DS_ELEICAO,20721,2,Eleições Gerais Estaduais 2026,20695,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DT_ELEICAO,20721,1,04/10/2026,20721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TP_ABRANGENCIA,20721,2,ESTADUAL,20695,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SG_UF,20721,28,SP,2610,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SG_UE,20721,28,SP,2610,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NM_UE,20721,28,SÃO PAULO,2610,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD_CARGO,20721.0,NaN,NaN,NaN,6.622895,0.891706,1.0,6.0,7.0,7.0,10.0
DS_CARGO,20721,10,DEPUTADO ESTADUAL,11191,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SQ_CANDIDATO,20721.0,NaN,NaN,NaN,152989850090.7099,72726309879.593338,10002532416.0,90002546235.0,160002546818.0,210002541957.0,280002553884.0
NR_CANDIDATO,20721.0,NaN,NaN,NaN,18493.832296,19394.409448,10.0,2708.0,12010.0,30121.0,80800.0
NM_CANDIDATO,20721,20623,ANTONIO CARLOS DA SILVA,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NM_URNA_CANDIDATO,20721,20209,MARIA HELENA,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NM_SOCIAL_CANDIDATO,20721,55,#NULO,20667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NR_CPF_CANDIDATO,20721.0,NaN,NaN,NaN,34353687051.026493,31369847344.951302,1046047.0,5756661611.0,25184440330.0,61840424087.0,99983494515.0
DS_EMAIL,20721,1,NÃO DIVULGÁVEL,20721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD_SITUACAO_CANDIDATURA,20721.0,NaN,NaN,NaN,-3.0,0.0,-3.0,-3.0,-3.0,-3.0,-3.0
DS_SITUACAO_CANDIDATURA,20721,1,#NE,20721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TP_AGREMIACAO,20721,3,PARTIDO ISOLADO,13969,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NR_PARTIDO,20721.0,NaN,NaN,NaN,31.138314,18.60651,10.0,15.0,27.0,44.0,80.0
SG_PARTIDO,20721,30,PL,1635,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NM_PARTIDO,20721,30,PARTIDO LIBERAL,1635,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NR_FEDERACAO,20721.0,NaN,NaN,NaN,30.862893,47.628005,-1.0,-1.0,-1.0,101.0,104.0
NM_FEDERACAO,20721,6,#NULO,14313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SG_FEDERACAO,20721,6,#NULO,14313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DS_COMPOSICAO_FEDERACAO,20721,6,#NULO,14313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SQ_COLIGACAO,20721.0,NaN,NaN,NaN,152989108181.479797,72726309585.356018,10001800109.0,90001800809.0,160001800844.0,210001800596.0,280001801455.0
NM_COLIGACAO,20721,97,PARTIDO ISOLADO,13969,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DS_COMPOSICAO_COLIGACAO,20721,126,PL,1559,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SG_UF_NASCIMENTO,20721,28,SP,2526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DT_NASCIMENTO,20721,11743,01/12/1982,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NR_TITULO_ELEITORAL_CANDIDATO,20721.0,NaN,NaN,NaN,77315752384.366013,85981768180.971298,1031317.0,19910421481.0,47492571104.0,99522070310.0,888497440302.0
CD_GENERO,20721.0,NaN,NaN,NaN,2.697746,0.953251,2.0,2.0,2.0,4.0,4.0
DS_GENERO,20721,2,MASCULINO,13492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD_GRAU_INSTRUCAO,20721.0,NaN,NaN,NaN,7.086965,1.315436,2.0,6.0,8.0,8.0,8.0
DS_GRAU_INSTRUCAO,20721,7,SUPERIOR COMPLETO,12136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD_ESTADO_CIVIL,20721.0,NaN,NaN,NaN,3.139762,2.482946,1.0,1.0,3.0,3.0,9.0
DS_ESTADO_CIVIL,20721,5,CASADO(A),10394,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD_COR_RACA,20721.0,NaN,NaN,NaN,1.895613,0.971436,1.0,1.0,2.0,3.0,5.0
DS_COR_RACA,20721,5,BRANCA,10281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD_OCUPACAO,20721.0,NaN,NaN,NaN,391.015202,311.206926,101.0,169.0,257.0,532.0,999.0
DS_OCUPACAO,20721,210,OUTROS,2760,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD_SIT_TOT_TURNO,20721.0,NaN,NaN,NaN,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0
DS_SIT_TOT_TURNO,20721,1,#NULO,20721,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df["DS_CARGO"].value_counts()

DS_CARGO
DEPUTADO ESTADUAL     11191
DEPUTADO FEDERAL       7707
DEPUTADO DISTRITAL      429
2º SUPLENTE             328
1º SUPLENTE             325
SENADOR                 316
VICE-GOVERNADOR         201
GOVERNADOR              198
PRESIDENTE               13
VICE-PRESIDENTE          13
Name: count, dtype: int64

In [23]:
df["SG_PARTIDO"].value_counts().head(10)

SG_PARTIDO
PL              1635
MDB             1407
REPUBLICANOS    1300
NOVO            1293
PODE            1229
PSD             1126
PDT             1106
PT              1102
PSDB            1068
AVANTE           972
Name: count, dtype: int64